<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 *
 * @package     Hyperpay
 * @copyright   Copyright (c) 2014 HYPERPAY
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * 
 */
?>
<?php
	$langs = Mage::helper('hyperpay')->getLocaleIsoCode(); 
	switch ($langs) {
		case 'de':
		case 'fr':
		case 'nl':
		case 'it':
		  $lang = $langs;
		  break;

		default:
		  $lang='en';
	}
?>
<script src="<?php echo Mage::getSingleton('customer/session')->getJsUrl().$lang;?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/hyperpay/jquery-1.10.2.min.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/hyperpay/hyperpay_cc.js')?>" type="text/javascript"></script>
<link href="<?php echo $this->getSkinUrl('css/hyperpay/formbank.css')?>" rel="stylesheet" type="text/css">


<form action="<?php echo Mage::getSingleton('customer/session')->getIframeFrontendResponse();?>" id="<?php echo Mage::getSingleton('customer/session')->getIframeToken();?>">VISA MASTER MAESTRO</form>
<input class="cust_name" value="<?php echo Mage::getSingleton('customer/session')->getIframeName();?>" type="hidden">
<input class="img_url" value="<?php echo $this->getSkinUrl('images/hyperpay');?>" type="hidden">

<?php
	if ($lang == "de")
	{
		echo '<a class="linkhyperpay" href="http://www.hyperpay.com" target="blank">';
		echo '<a class="linkhyperpayoverlay" href="http://www.hyperpay.com" target="blank">';
	}
	else
	{
		echo '<a class="linkhyperpay" href="http://www.hyperpay.com" target="blank">';
		echo '<a class="linkhyperpayoverlay" href="http://www.hyperpay.com" target="blank">';
	}
?>

<span class="txtSSL"><?php echo Mage::helper('hyperpay')->__('This page is SSL-encrypted in order to protect your data.'); ?></span>
<span class="txtCardNumber"><?php echo Mage::helper('hyperpay')->__('Card number') ?></span>
<span class="txtExpires"><?php echo Mage::helper('hyperpay')->__('Expires Month / Year') ?></span>
<span class="txtCvc"><?php echo Mage::helper('hyperpay')->__('CVC-Code') ?></span>
<span class="txtHelp"><?php echo Mage::helper('hyperpay')->__('Help') ?></span>
<span class="txtWhatCvc"><h4><?php echo Mage::helper('hyperpay')->__('What is the Card Validation Code?') ?></h4></span>
<span class="txtCards"><h4><?php echo Mage::helper('hyperpay')->__('Visa, MasterCard and Maestro :') ?></h4></span>
<span class="txtThreeDigits"><?php echo Mage::helper('hyperpay')->__('The last three digits in or next to the signature field on the back of your card.') ?></span>
<a class="btnCustom btnCustomCancel" href="<?php echo $this->getBaseUrl()?>checkout/onepage"><?php echo Mage::helper('hyperpay')->__('Cancel') ?></a>
<input type="submit" value="<?php echo Mage::helper('hyperpay')->__('Confirm') ?>" class="btnCustom btnCustomSubmit">
