<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 *
 * @package     Hyperpay
 * @copyright   Copyright (c) 2014 HYPERPAY
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * 
 */
?>
<?php
	$langs = Mage::helper('hyperpay')->getLocaleIsoCode(); 
	switch ($langs) {
		case 'de':
		case 'fr':
		case 'nl':
		case 'it':
		  $lang = $langs;
		  break;

		default:
		  $lang='en';
	}
	$brand = Mage::getSingleton('customer/session')->getIframeBrand();
?>
<script src="<?php echo Mage::getSingleton('customer/session')->getJsUrl().$lang;?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/hyperpay/jquery-1.10.2.min.js')?>" type="text/javascript"></script>

<style>
	.style-SOFORTUEBERWEISUNG {
		background-position : 0px 0px;
		background-image : url('<?php echo $this->getSkinUrl('images/hyperpay/sofortlogo.png')?>');
		height : 47px;
		margin-left : 5px;
	}
</style>
	
<?php if ($brand == "PAYPAL") { ?>
	<style>
		button.customDirectSubmit {
			display:none;
		}
		.spinner {
			display:none;
		}
	</style>
	<script>
		cnp_jQuery(document).on('copyandpay:ready', function() {
			$(".customDirectSubmit").click();
		});
	</script>
<?php } ?>

<form action="<?php echo Mage::getSingleton('customer/session')->getIframeFrontendResponse();?>" id="<?php echo Mage::getSingleton('customer/session')->getIframeToken();?>"><?php echo $brand;?></form>
